package com.axiastudio.ooops.filters;

import java.util.HashMap;
import java.util.Map;

/**
 * User: tiziano
 * Date: 03/06/14
 * Time: 16:49
 */
public class Filters {

    public String getUIName(String key){
        return filters.get(key);
    }

    private static final Map<String, String> filters;
    static
    {
        filters = new HashMap<String, String>();
        filters.put("writer_Rich_Text_Format", "Rich Text Format");
        filters.put("svg_Scalable_Vector_Graphics", "SVG - Scalable Vector Graphics");
        filters.put("pct_Mac_Pict", "PCT - Mac Pict");
        filters.put("eps_Encapsulated_PostScript", "EPS - Encapsulated PostScript");
        filters.put("calc_Lotus", "Lotus 1-2-3");
        filters.put("gif_Graphics_Interchange", "GIF - Graphics Interchange Format");
        filters.put("pcx_Zsoft_Paintbrush", "PCX - Zsoft Paintbrush");
        filters.put("calc_DIF", "Data Interchange Format");
        filters.put("writer_web_HTML", "HTML Document (OpenOffice.org Writer)");
        filters.put("graphic_SWF", "Macromedia Flash (SWF)");
        filters.put("writer_MS_WinWord_60", "Microsoft Word 6.0");
        filters.put("chart_StarOffice_XML_Chart", "OpenOffice.org 1.0 Chart");
        filters.put("impress8", "ODF Presentation");
        filters.put("tif_Tag_Image_File", "TIFF - Tagged Image File Format");
        filters.put("writer_MS_Word_95", "Microsoft Word 95");
        filters.put("wmf_MS_Windows_Metafile", "WMF - Windows Metafile");
        filters.put("writer_MS_Word_97", "Microsoft Word 97/2000/XP");
        filters.put("writerglobal8", "ODF Master Document");
        filters.put("writer_web_HTML", "HTML Document");
        filters.put("impress_StarOffice_XML_Impress_Template", "OpenOffice.org 1.0 Presentation Template");
        filters.put("XHTML_File", "XHTML");
        filters.put("writer_MS_Word_97_Vorlage", "Microsoft Word 97/2000/XP Template");
        filters.put("writer_MS_Word_95_Vorlage", "Microsoft Word 95 Template");
        filters.put("draw_WordPerfect_Graphics", "WordPerfect Graphics");
        filters.put("writer_MS_Word_2007_Template", "Microsoft Word 2007 XML Template");
        filters.put("calc8_template", "ODF Spreadsheet Template");
        filters.put("XHTML_File", "XHTML");
        filters.put("sgf_StarOffice_Writer_SGF", "SGF - StarWriter Graphics Format");
        filters.put("draw_ODG_FlatXML", "OpenDocument Drawing (Flat XML)");
        filters.put("emf_MS_Windows_Metafile", "EMF - Enhanced Metafile");
        filters.put("Unified_Office_Format_presentation", "Unified Office Format presentation");
        filters.put("calc_StarOffice_XML_Calc", "OpenOffice.org 1.0 Spreadsheet");
        filters.put("pdf_Portable_Document_Format", "PDF - Portable Document Format");
        filters.put("writer_web_HTML", "Web Page Query (OpenOffice.org Calc)");
        filters.put("writer_web_StarOffice_XML_Writer_Web_Template", "OpenOffice.org 1.0 HTML Template");
        filters.put("writer8_template", "ODF Text Document Template");
        filters.put("pbm_Portable_Bitmap", "PBM - Portable Bitmap");
        filters.put("calc_StarOffice_XML_Calc_Template", "OpenOffice.org 1.0 Spreadsheet Template");
        filters.put("writer_web_HTML_help", "Help content");
        filters.put("svm_StarView_Metafile", "SVM - StarView Metafile");
        filters.put("calc_ODS_FlatXML", "OpenDocument Spreadsheet (Flat XML)");
        filters.put("pdf_Portable_Document_Format", "PDF - Portable Document Format");
        filters.put("pdf_Portable_Document_Format", "PDF - Portable Document Format");
        filters.put("chart8", "ODF Chart");
        filters.put("writer_LotusWordPro_Document", "Lotus WordPro Document");
        filters.put("writer_MIZI_Hwp_97", "Hangul WP 97");
        filters.put("writer_MS_Works_Document", "Microsoft Works Document");
        filters.put("draw_StarOffice_XML_Draw", "OpenOffice.org 1.0 Drawing");
        filters.put("xpm_XPM", "XPM - X PixMap");
        filters.put("xpm_XPM", "XPM - X PixMap");
        filters.put("pcd_Photo_CD_Base16", "PCD - Kodak Photo CD (192x128)");
        filters.put("math8", "ODF Formula");
        filters.put("calc_MS_Excel_5095", "Microsoft Excel 5.0 (OpenOffice.org Writer)");
        filters.put("Unified_Office_Format_spreadsheet", "Unified Office Format spreadsheet");
        filters.put("pct_Mac_Pict", "PCT - Mac Pict");
        filters.put("MediaWiki", "MediaWiki");
        filters.put("writerweb8_writer_template", "HTML Document Template");
        filters.put("writer8", "ODF Text Document");
        filters.put("writer8", "OpenOffice.org Text (OpenOffice.org Writer/Web)");
        filters.put("writer_web_HTML", "HTML Document (OpenOffice.org Calc)");
        filters.put("ppm_Portable_Pixelmap", "PPM - Portable Pixelmap");
        filters.put("calc_SYLK", "SYLK");
        filters.put("MS Excel 2007 XML", "Microsoft Excel 2007 XML");
        filters.put("met_OS2_Metafile", "MET - OS/2 Metafile");
        filters.put("impress_ODP_FlatXML", "OpenDocument Presentation (Flat XML)");
        filters.put("graphic_HTML", "HTML Document (OpenOffice.org Impress)");
        filters.put("draw_StarOffice_XML_Draw", "OpenOffice.org 1.0 Drawing (OpenOffice.org Impress)");
        filters.put("writer_WordPerfect_Document", "WordPerfect Document");
        filters.put("writer_Lotus_1_2_3_10_WIN_StarWriter", "Lotus 1-2-3 1.0 WIN (OpenOffice.org Writer)");
        filters.put("emf_MS_Windows_Metafile", "EMF - Enhanced Metafile");
        filters.put("writer_DocBook_File", "DocBook");
        filters.put("draw_StarOffice_XML_Draw_Template", "OpenOffice.org 1.0 Drawing Template");
        filters.put("calc_MS_Excel_95_VorlageTemplate", "Microsoft Excel 95 Template");
        filters.put("writer_StarOffice_XML_Writer", "OpenOffice.org 1.0 Text Document (OpenOffice.org Writer/Web)");
        filters.put("writer_Rich_Text_Format", "Rich Text Format (OpenOffice.org Calc)");
        filters.put("dxf_AutoCAD_Interchange", "DXF - AutoCAD Interchange Format");
        filters.put("MS Excel 2007 Binary", "Microsoft Excel 2007 Binary");
        filters.put("impress8_template", "ODF Presentation Template");
        filters.put("MediaWiki", "MediaWiki");
        filters.put("calc_MS_Excel_40_VorlageTemplate", "Microsoft Excel 4.0 Template");
        filters.put("MS PowerPoint 2007 XML Template", "Microsoft PowerPoint 2007 XML Template");
        filters.put("ras_Sun_Rasterfile", "RAS - Sun Raster Image");
        filters.put("writer_Text", "Text Encoded (OpenOffice.org Writer/Web)");
        filters.put("calc_MS_Excel_40", "Microsoft Excel 4.0");
        filters.put("calc_QPro", "Quattro Pro 6.0");
        filters.put("calc_MS_Excel_5095", "Microsoft Excel 5.0");
        filters.put("xpm_XPM", "XPM - X PixMap");
        filters.put("wmf_MS_Windows_Metafile", "WMF - Windows Metafile");
        filters.put("tif_Tag_Image_File", "TIFF - Tagged Image File Format");
        filters.put("svm_StarView_Metafile", "SVM - StarView Metafile");
        filters.put("svg_Scalable_Vector_Graphics", "SVG - Scalable Vector Graphics");
        filters.put("ras_Sun_Rasterfile", "RAS - Sun Raster Image");
        filters.put("ppm_Portable_Pixelmap", "PPM - Portable Pixelmap");
        filters.put("png_Portable_Network_Graphic", "PNG - Portable Network Graphic");
        filters.put("pgm_Portable_Graymap", "PGM - Portable Graymap");
        filters.put("pdf_Portable_Document_Format", "PDF - Portable Document Format");
        filters.put("pct_Mac_Pict", "PCT - Mac Pict");
        filters.put("pbm_Portable_Bitmap", "PBM - Portable Bitmap");
        filters.put("met_OS2_Metafile", "MET - OS/2 Metafile");
        filters.put("jpg_JPEG", "JPEG - Joint Photographic Experts Group");
        filters.put("gif_Graphics_Interchange", "GIF - Graphics Interchange Format");
        filters.put("eps_Encapsulated_PostScript", "EPS - Encapsulated PostScript");
        filters.put("emf_MS_Windows_Metafile", "EMF - Enhanced Metafile");
        filters.put("bmp_MS_Windows", "BMP - Windows Bitmap");
        filters.put("writer_Text", "Text Encoded (OpenOffice.org Master Document)");
        filters.put("png_Portable_Network_Graphic", "PNG - Portable Network Graphic");
        filters.put("psd_Adobe_Photoshop", "PSD - Adobe Photoshop");
        filters.put("png_Portable_Network_Graphic", "PNG - Portable Network Graphic");
        filters.put("draw8", "ODF Drawing (Impress)");
        filters.put("pcd_Photo_CD_Base4", "PCD - Kodak Photo CD (384x256)");
        filters.put("writer_Text", "Text");
        filters.put("pcd_Photo_CD_Base", "PCD - Kodak Photo CD (768x512)");
        filters.put("XHTML_File", "XHTML");
        filters.put("pwp_PlaceWare", "PWP - PlaceWare");
        filters.put("met_OS2_Metafile", "MET - OS/2 Metafile");
        filters.put("writer_MS_WinWord_5", "Microsoft WinWord 5");
        filters.put("writer_Text_encoded", "Text Encoded");
        filters.put("writer_StarOffice_XML_Writer", "OpenOffice.org 1.0 Text Document");
        filters.put("calc_MS_Excel_5095_VorlageTemplate", "Microsoft Excel 5.0 Template");
        filters.put("pgm_Portable_Graymap", "PGM - Portable Graymap");
        filters.put("writer_T602_Document", "T602 Document");
        filters.put("math_StarOffice_XML_Math", "OpenOffice.org 1.0 Formula");
        filters.put("calc_MS_Excel_95", "Microsoft Excel 95 (OpenOffice.org Writer)");
        filters.put("writer_web_HTML", "HTML (Writer/Global)");
        filters.put("math_MathML_XML_Math", "MathML 1.01");
        filters.put("MS Excel 2007 XML Template", "Microsoft Excel 2007 XML Template");
        filters.put("impress_StarOffice_XML_Impress", "OpenOffice.org 1.0 Presentation");
        filters.put("calc_MS_Excel_2003_XML", "Microsoft Excel 2003 XML");
        filters.put("sgv_StarDraw_20", "SGV - StarDraw 2.0");
        filters.put("writer_ODT_FlatXML", "OpenDocument Text (Flat XML)");
        filters.put("XHTML_File", "XHTML");
        filters.put("writer8", "ODF Text Document");
        filters.put("pbm_Portable_Bitmap", "PBM - Portable Bitmap");
        filters.put("svm_StarView_Metafile", "SVM - StarView Metafile");
        filters.put("math_MathType_3x", "MathType3.x");
        filters.put("impress_CGM_Computer_Graphics_Metafile", "CGM - Computer Graphics Metafile");
        filters.put("pdf_Portable_Document_Format", "PDF - Portable Document Format");
        filters.put("draw8_template", "ODF Drawing Template");
        filters.put("calc_Text_txt_csv_StarCalc", "Text CSV");
        filters.put("gif_Graphics_Interchange", "GIF - Graphics Interchange Format");
        filters.put("impress_MS_PowerPoint_97", "Microsoft PowerPoint 97/2000/XP");
        filters.put("xbm_X_Consortium", "XBM - X Bitmap");
        filters.put("tif_Tag_Image_File", "TIFF - Tagged Image File Format");
        filters.put("bmp_MS_Windows", "BMP - Windows Bitmap");
        filters.put("tga_Truevision_TARGA", "TGA - Truevision Targa");
        filters.put("calc_MS_Excel_97_VorlageTemplate", "Microsoft Excel 97/2000/XP Template");
        filters.put("ras_Sun_Rasterfile", "RAS - Sun Raster Image");
        filters.put("calc_dBase", "dBASE");
        filters.put("writer_Text", "Text (OpenOffice.org Writer/Web)");
        filters.put("writer_Lotus_1_2_3_10_DOS_StarWriter", "Lotus 1-2-3 1.0 DOS (OpenOffice.org Writer)");
        filters.put("Unified_Office_Format_text", "Unified Office Format text");
        filters.put("ppm_Portable_Pixelmap", "PPM - Portable Pixelmap");
        filters.put("MS PowerPoint 2007 XML", "Microsoft PowerPoint 2007 XML");
        filters.put("calc8", "ODF Spreadsheet");
        filters.put("svg_Scalable_Vector_Graphics", "SVG - Scalable Vector Graphics");
        filters.put("writer_globaldocument_StarOffice_XML_Writer_GlobalDocument", "OpenOffice.org 1.0 Master Document");
        filters.put("pdf_Portable_Document_Format", "PDF - Portable Document Format");
        filters.put("jpg_JPEG", "JPEG - Joint Photographic Experts Group");
        filters.put("writer_MS_Word_2007", "Microsoft Word 2007 XML");
        filters.put("graphic_SWF", "Macromedia Flash (SWF)");
        filters.put("pgm_Portable_Graymap", "PGM - Portable Graymap");
        filters.put("writer_StarOffice_XML_Writer", "OpenOffice.org 1.0 Text Document");
        filters.put("writer_MS_Word_2003_XML", "Microsoft Word 2003 XML");
        filters.put("writer_StarOffice_XML_Writer_Template", "OpenOffice.org 1.0 Text Document Template");
        filters.put("calc_MS_Excel_40", "Microsoft Excel 4.0 (OpenOffice.org Writer)");
        filters.put("impress_MS_PowerPoint_97_Vorlage", "Microsoft PowerPoint 97/2000/XP Template");
        filters.put("pdf_Portable_Document_Format", "PDF - Portable Document Format");
        filters.put("graphic_HTML", "HTML Document (OpenOffice.org Draw)");
        filters.put("bmp_MS_Windows", "BMP - Windows Bitmap");
        filters.put("calc_MS_Excel_95", "Microsoft Excel 95");
        filters.put("draw8", "ODF Drawing");
        filters.put("wmf_MS_Windows_Metafile", "WMF - Windows Metafile");
        filters.put("calc_MS_Excel_97", "Microsoft Excel 97/2000/XP");
        filters.put("jpg_JPEG", "JPEG - Joint Photographic Experts Group");
        filters.put("eps_Encapsulated_PostScript", "EPS - Encapsulated PostScript");
    }

}
